### ISSUE TITLE
Using Defer Attribute to Load AdSense Javascript

### ISSUE THREAD

**Issue by adarshmadrecha** [YunYouJun/vuepress-plugin-google-adsense#1]
To improve user experience, it would be awesome to use defer attribute on script loading

**Comment by YunYouJun** [comment]
Hello, thanks for your advice.

I use `async` in script, so we may not need `defer`.
I did this because Google's sample code only uses `async`.

You can see it in next links.
https://support.google.com/adsense/answer/9274634
https://support.google.com/adsense/answer/9274516

If you think we should use `defer`, please tell me the detailed reason.  Thank you very much.

**Comment by YunYouJun** [comment]
I closed this issue.
If you have any question about it, you can reopen it.

**Comment by adarshmadrecha** [comment]
Yes, you are right, no need for `defer`
